lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-esx60-graph.js
lib/graphs/install-rhel-graph.js

Fix ODR-237, add 1 hour timeout for OS bootstrap task to avoid workflow hang for a long time.
https://hwjiraprd01.corp.emc.com/browse/ODR-273

Fix ODR273: Add 1 hour timeout for ESXi/RHEL/CentOS bootstrap

---

lib/graphs/create-megaraid-graph.js
lib/graphs/delete-megaraid-graph.js
spec/lib/graphs/create-megaraid-graph-spec.js
spec/lib/graphs/delete-megaraid-graph-spec.js

This PR is to add graph for create or delete raid then refresh the MegaRAID catalog
Dependency PR https://github.com/RackHD/on-tasks/pull/76
@RackHD/corecommitters @iceiilin @pengz1 @sunnyqianzhang

MAG-289 [ORFS-97] Add create delete raid graph

---

index.js
lib/context.js
lib/scheduler.js
lib/task-graph.js

updating mapping to more constricted set of logs per
https://github.com/RackHD/RackHD/issues/34
**NOTE**: Requires https://github.com/RackHD/on-core/pull/48 to be
committed prior as it adds the synonym 'critical' to the existing 'crit'
level.

rationalizing logs

---

lib/graphs/discovery-mgmt-graph.js

Set mgmt server discovery tasks work in serial manner to avoid task scheduling competition. Otherwise a mongoError is likely to report with a long dump log:
2016-01-12T09:49:55.806Z [on-taskgraph] [TaskGraph.TaskGraph] [Server] Error persisting Task Graph state
-> /lib/task-graph.js:483     
"""
Details:  { name: 'MongoError',
message: 'Object #<Object> has no method \'value\'',
driver: true,
ok: 1,
n: 0,
code: 14,
errmsg: 'Object #<Object> has no method \'value\'',
writeErrors: 
[ { index: 0,
code: 14,
errmsg: 'Object #<Object> has no method \'value\'' } ] }
"""

Set mgmt server discovery task in serial manner

---

lib/graphs/discovery-mgmt-graph.js

The same PR to 1.1.0 branch as https://github.com/RackHD/on-taskgraph/pull/43 (has merged) to master branch. Set mgmt server discovery tasks work in serial manner to avoid task scheduling competition.

Set mgmt server discovery task to run in a serial manner

---

debian/control

Need to specify the ipmitool version to avoid a current bug in version 1.8.13-1ubuntu0.6 of ipmitool that breaks the fru command. This change should be merged with the similar PRs in onrack-infra onrack-base, and on-taskgraph 1.1.0 branch.

Specify version 1.8.13-1 for ipmitool package

---

debian/control

Sigh, reverting yet again.  Think we understand more, but not ready to apply fix yet.
Reverts RackHD/on-taskgraph#54

Revert "Specify version 1.8.13-1 for ipmitool package"

---

lib/graphs/discovery-refresh-graph.js

Adds the discovery-refresh-graph.js graph.  This graph reboots a node and runs discovery.
@benbp

ON-2719 Adds discovery-refresh-graph.js

---

Dockerfile
docker_entry.sh

Dockerfile for building on-taskgraph image.
Needed to add `docker_entry.sh` in order to run `dhcpd` and `node`.

Add Dockerfile

---

.dockerignore
Dockerfile
docker_entry.sh

REQUIRES: https://github.com/RackHD/on-core/pull/79
* Switched rackhd/on-core to use an alpine linux base image.
* Use CMD instead of ENTRYPOINT for easier debugging.

Update Dockerfile for Alpine Linux

---

lib/graphs/discovery-refresh-delayed-graph.js
lib/graphs/discovery-refresh-immediate-graph.js

1) discovery-refresh-delayed-graph.js : starts refresh
without first doing a reset.
2) discovery-refresh-immediate-graph.js : starts refresh
by first doing a reset.
Removed existing RunSKU portion of these workflows.

ODR-547 Established new refresh graphs

---

lib/task-runner.js
spec/lib/task-runner-spec.js

Publish error messages for finished tasks so that they get persisted into the graph document. This makes it easier to debug failed workflows. Minor feature regression.
Requires https://github.com/RackHD/on-core/pull/92 and https://github.com/RackHD/on-tasks/pull/135
@RackHD/corecommitters @VulpesArtificem

Publish error message with task finished events

---

.gitignore
HWIMO-BUILD

npm prune --production doesn't work correctly in version 1.3.10. It ends up removing the redfish-node module form on-tasks node_modules which is needed for on-taskgraph.
To work around this, we just change the npm install to npm install --production since we prune immediately after the install anyway.

HWIMO-BUILD: Work around npm 1.3.10 bug with prune.

---

lib/graphs/dell-racadm-get-config-catalog-graph.js
spec/lib/graphs/dell-racadm-get-config-catalog-graph-spec.js

This PR is depend on another PR in the on-tasks repo:
https://github.com/RackHD/on-tasks/pull/137
The root cause of  continuous-integration/travis-ci/pr  is identified in the following link:
https://travis-ci.org/RackHD/on-taskgraph/jobs/113595827
It has nothing to do with this PR. @jlongever, could you please help take a look? 
1) Graph Library "before all" hook:
Error: Cannot find module 'redfish-node'
at require (internal/module.js:16:19)
at Object.<anonymous> (node_modules/on-tasks/lib/jobs/redfish-discovery.js:6:15)
The jenkins failure is due to the dependency on the tasks as described in above link
==> Rebase the code to the latest, and everything got fixed

Add taskgraph for getting configure catalog with dell racadm tool

---

Dockerfile

These libraries were missing in the alpine linux base image, they are used by taskgraph.

Adds ipmitool and snmptool to Dockerfile

---

lib/graphs/redfish-discovery-graph.js

- Modify the redfish discovery graph to also catalog EMC
elements on freshly added chassis/systems when auto
catalog is enabled

modify redfish discovery to optionally catalog EMC elements

---

lib/graphs/flash-quanta-all-graph.js
lib/graphs/flash-quanta-bios-graph.js
lib/graphs/flash-quanta-bmc-graph.js

"catalog ami" task before flashing Quanta BIOS would fail in command "./afulnx_64" in microkernel complaining no kernel source exist, thus the following "flash BIOS" task would not be executed. Overwriting the "bootstrap ubuntu" option to 3.13.0 version solve this problem.
Change to use megaraid catalog instead of ami for post-megaraid-update-catalog. Change to use bmc catalog instead of ami for post-bmc-update-catalog.
@benbp

Overwrite kernel and initrd file to 3.13.0 when flashing quanta

---

lib/graphs/install-esx-graph.js

Add default `repo` for install ESXi graph to align with other OSs, such as [RHEL](https://www.github.com/RackHD/on-taskgraph/blob/master/lib/graphs/install-rhel-graph.js#L11), [CentOS](https://www.github.com/RackHD/on-taskgraph/blob/master/lib/graphs/install-centos-graph.js#L11), [SUSE](https://www.github.com/RackHD/on-taskgraph/blob/master/lib/graphs/install-suse-graph.js#L11).
The benefit we get is that if user follows our default address to setup the OS repo, then only the `version` is required for OS bootstrap, such make the OS bootstrap pretty simple.
@RackHD/corecommitters @pengz1 @iceiilin @WangWinson @cgx027 @sunnyqianzhang

add default 'repo' in install esxi graph

---

lib/graphs/cisco-switch-discovery-graph.js
lib/graphs/switch-active-discovery-sku-graph.js
lib/graphs/switch-discovery-post-sku-hooks-graph.js

This PR is one of a few changesets that add functionality for active discovery and configuration of network switches during their bootstrap processes (Cisco POAP, Arista ZTP, etc.). 
I am adding a bundle of what are intended to be RackHD built-in graphs (switch-active-discovery-sku-graph.js and switch-discovery-post-sku-hooks-graph.js) along with some example graphs for cisco cataloging and startup configuration (cisco-switch-discovery-graph.js and deploy-cisco-nexus3000-switch-startup-config-graph.js).
I'll put up a docs PR tomorrow, but the intent of these scripts is that the main switch active discovery graph calls multiple vendor specific sub-graphs. First the cataloging, the implementation of which varies vendor to vendor, and second any SKU-specific graphs that should be run. This …

Add switch/cisco switch discovery graphs

---

lib/graphs/flash-quanta-bmc-graph.js

Overwrite kernel and initrd version to 3.13.0. The tool (soc_flash) for updating BMC is not relied on kernel, while the ipmitool used for catalog before and after updating uses ipmi driver in kernel. 
Remove reboot node task at the end of this workflow. The operation is not a requirement for updating BMC, as suggested in the updating script provided by Quanta. Meanwhile, after updating, BMC network configuration is reset to default (DHCP), so this operation would fail in some network environment, if its IP is not assigned by DHCP server in RackHD control network. Per @zyoung51, there would be a story about saving the configuration before updating and applying it to the new BMC.

 Overwrite kernel and initrd file to 3.13.0 in quanta bmc update workflow

---

lib/task-graph-runner.js

depends on https://github.com/RackHD/on-core/pull/132
changed so that we only create the necessary compound indexes in task-graph-runner; other indexes and uniqueness enforcement have been moved to the waterline models.  

added unique flags to indexObject

---

lib/graphs/install-esx-graph.js

The ESXi installation graph completes during the initial kickstart
download to resolve an issue with multiple reboots.  Add an additional
completionUri wait into the graph to wait for a second Uri trigger
which occurs during the ESXi firstboot script
Depends on: https://github.com/RackHD/on-tasks/pull/196

Fix issue with ESXi installation early completion

---

lib/graphs/install-esx-graph.js

This addresses an issue where we end up doing SSH validation before we're ready during an ESXi install. These changes support a script that hits an API route to verify the OS is up and running during the %firstboot phase of installation and on post installation reboot.
Builds on the update made in #98. ESXi does an extra reboot in our %firstboot configuration, so the workflow needs to handle tracking both reboot states in order to avoid doing SSH validation too early (e.g. we might validate the system is up and listening during firstboot right before it reboots, instead of waiting for the last reboot before validation).
Supports RackHD/on-http#283
Requires RackHD/on-tasks#210
@RackHD/corecommitters @heckj @zyoung51 @VulpesArtificem @johren @stuart-stanley @richav1 @amymullins

Add completion URI wait task to esx installer graph

---

lib/graphs/install-rhel-graph.js

Adds wait for reboot and SSH validation tasks to the RHEL installer graph (identical process to the CentOS installer updates made last week).
@RackHD/corecommitters @heckj @johren @richav1

Add SSH validation to RHEL install graph

---

lib/graphs/switch-discovery-graph.js

for RackHD/RackHD#236
@RackHD/corecommitters @johren 
adds a task to the switch discovery workflow to add all of the switch's interface mac addresses to the lookups collection
depends on https://github.com/RackHD/on-tasks/pull/220

[1.2] updated switch discovery to update lookups

---

lib/graphs/switch-discovery-graph.js

for https://github.com/RackHD/RackHD/issues/236
@RackHD/corecommitters @johren 
adds a task to the switch discovery workflow to add all of the switch's interface mac addresses to the lookups collection
depends on https://github.com/RackHD/on-tasks/pull/219

updated switch discovery to update lookups

---

lib/graphs/flash-quanta-bios-graph.js
lib/graphs/flash-quanta-bmc-graph.js
lib/graphs/write-quanta-bios-nvram-graph.js

To address ODR 728, using 3.16 microkernel for FW update, and pulling the necessary tools in a newly-added task.
Another change is to add reboot node after flashing BMC. 
Previous workflow didn't include this step since BMC network restores to default after FW update, and keeping the node in microkernel can help the user to set the BMC LAN settings.
After a restore step has been added to BMC FW update (https://github.com/RackHD/on-http/pull/316, https://github.com/RackHD/on-tasks/pull/221), the reboot task can be added to the workflow.
Details in related PR:
https://github.com/RackHD/on-tasks/pull/221

[1.2] Pull quanta fw update tools instead of using 3.13 microkernel

---

lib/graphs/bootstrap-bmc-credentials-remove-graph.js
lib/graphs/remove-bmc-credentials-graph.js
spec/lib/graphs/bootstrap-bmc-credentials-remove-graph-spec.js
spec/lib/graphs/remove-bmc-credentials-graph-spec.js

- Allow the user to remove added BMC users to restore defaults
- note: This is part of decommissioning a node story. 
depends on: https://github.com/RackHD/on-tasks/pull/233
depends on: https://github.com/RackHD/on-http/pull/320

Remove BMC user credentials graph

---

lib/service-graph.js

To improve consistency, since graphs created from on-http will start in a running state. Before the service graphs would be pending.

Set service graph status to running.

---

lib/graphs/discovery-graph.js

Add a task to set bootdev to pxe, so that the following run-sku-graph
will be run following a pxe boot. Please also refer to
lib/graph/discovery-sku-graph.js

Modify Graph.Discovery to support sku discovery.

---

lib/graphs/discovery-graph.js
lib/graphs/discovery-mgmt-graph.js
lib/graphs/pdu-discovery-graph.js
lib/graphs/switch-discovery-graph.js

one part of spec https://github.com/RackHD/RackHD/wiki/proposal-AMQP-notifications-on-node-discovery-or-inaccessibility, node remove and inaccessible alert will be in a following PR
depends on PRs: https://github.com/RackHD/on-core/pull/159 and https://github.com/RackHD/on-tasks/pull/240
@RackHD/corecommitters @WangWinson @iceiilin

Node discovered alert

---

lib/graphs/switch-discovery-graph.js

Issue: https://github.com/RackHD/RackHD/issues/295
This is a workaround for this issue for 1.2 only and is targeted at the one graph we use for switches that hit the race condition. All the change does is force the tasks to run in serial.
@RackHD/corecommitters @johren @derrickostertag

Race condition in task-graph can cause false success

---

lib/graphs/boot-livecd-graph.js
lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-rhel-graph.js
lib/graphs/install-suse-graph.js
spec/lib/graph-library-spec.js

When the task-schema upfront validation is enabled, all options in `defaults` will be passed into all tasks, this will cause some error in following case:
for example, if set version & repo to following format:
```
options: {
defaults: {
version: null,
repo: "{{api.server}}/{{options.version}}"
},
install-os: { }
}
```
if user passes the workflow options by following format:
```
{
options: {
install-os: {
version: 6.5,
repo: "xxxxx"
}
}
}
```
The `{version: null, repo: "{{api.server}}/{{options.version}}"}` will be passed to all other tasks except install-os. But the actual `version` & `repo` is only passed to 'install-os' tasks. So for all other tasks, the task options rendering will fail as the version is `null` for {{options.version}}.
My change is to remove these kind of data from …

tweak install-os graph's option to accommodate task-schema upfront validation

---

lib/graphs/install-photon-graph.js

For Photon installation workflow, version and repo options are only used for "install os" task. Move it out from default so that other task would not bother the render failure problem if the payload set the install-os task only.
@yyscamper @cgx027

Move version option from default to install-os task for photon os

---

extra/make-deb.sh

partial resolution for https://github.com/RackHD/RackHD/issues/310 - equiv changes would be needed for all the package repositories (on-http, on-dhcp-proxy, on-tftp, ..., etc)
Basically pulling the same scenario we used in https://github.com/RackHD/on-taskgraph/blob/master/HWIMO-BUILD to include an increasing version as we made additional builds on a branch. Date string is formatted to be increasing over time, and mapped (pretty closely) to the last commit merged into the branch.

proposed appending datestring to version in bintray packages

---

lib/graphs/discovery-redfish-system-graph.js

Temporarily disable ACPI in kernel bootstrap.
Updated to cleanup tasks, replace OBM reset task with shell reboot at the end of discovery.
@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya

Disable ACPI in kernel

---

lib/graphs/rancher-discovery-graph.js

depends on : https://github.com/RackHD/on-http/pull/392
depends on: https://github.com/RackHD/on-imagebuilder/pull/52/files
depends on : https://github.com/RackHD/on-tasks/pull/293
references:  
- https://osclouds.wordpress.com/2015/11/23/announcing-a-new-docker-based-hanlon-microkernel
- https://groups.google.com/forum/#!topic/rackhd/cSYYxhtPWY0

Create a discovery Graph that uses docker to run node discovery

---

lib/graphs/discovery-mgmtsku-graph.js
lib/graphs/discovery-sku-graph.js
lib/graphs/generate-tag-graph.js
lib/graphs/pdu-discovery-graph.js
lib/graphs/switch-active-discovery-sku-graph.js
lib/graphs/switch-discovery-graph.js

Requires https://github.com/RackHD/on-tasks/pull/320 and https://github.com/RackHD/on-http/pull/442 (interdependent).
@RackHD/corecommitters @heckj @pscharla

Pass an array of nodeIds to generate-tag task instead of a single nodeId

---

spec/lib/graph-library-spec.js

I see the on-taskgraph unit-test timeout in this build: https://travis-ci.org/RackHD/on-taskgraph/jobs/156150783
The reason is explained in my code.
Resolves https://github.com/RackHD/RackHD/issues/351
@RackHD/corecommitters @cgx027

increase timeout for graph library unit-testing

---

lib/task-graph-runner.js

Given this is our primary lookup field, we should probably index it.
@RackHD/corecommitters @VulpesArtificem @pscharla @zyoung51 @jlongever

Add an index for mongo graphobjects.instanceId

---

lib/graphs/bootstrap-decommission-node-graph.js
lib/graphs/examples/bootstrap-ubuntu-inline-graph-example.js
lib/graphs/examples/bootstrap-ubuntu-mocks-graph.js
lib/graphs/examples/bootstrap-ubuntu-overrides-graph-example.js
lib/graphs/flash-quanta-all-graph.js
lib/graphs/flash-quanta-bios-graph.js
lib/graphs/flash-quanta-bmc-graph.js
lib/graphs/flash-quanta-megaraid-graph.js
lib/graphs/intel-flashupdt-catalog-graph.js
lib/graphs/secure-erase-drive-graph.js
lib/graphs/write-quanta-bios-nvram-graph.js

Node discovery fails when using static file server, because basefs and overlayfs are always pulled from API_CB(api.server) rather than file.server.
The solution is to change BASEFS and OVERLAYFS to be full URL instead of file path.
* use overlayfsUri and overlayfsFile to replace overlayfs in task options
* use basefsUri and basefsFile to replace basefs in task options
@RackHD/corecommitters @iceiilin @cgx027 @panpan0000

fix discovery issue when using static file server

---

lib/graphs/install-centos-graph.js

Increased ssh-validation timeout to fix failing CentOS 7.0 max payload install.  
@keedya @uppalk1 @tannoa2 @RackHD/corecommitters

increase ssh-validation timeout to 60 sec for CentOS install

---

lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-photon-graph.js
lib/graphs/install-rhel-graph.js
lib/graphs/install-ubuntu-graph.js

Remove ssh validation from OS installation workflow since its funtionality for alerting the completion of OS intallation can be replaced with notification.
@RackHD/corecommitters @panpan0000 @iceiilin @johren @keedya

remove ssh validation from OS installation workflow

---

lib/graphs/arista-switch-discovery-graph.js
lib/graphs/brocade-switch-discovery-graph.js
lib/graphs/cisco-switch-discovery-graph.js
spec/lib/graph-library-spec.js

It's related with https://github.com/RackHD/on-tasks/pull/374 and https://github.com/RackHD/on-http/pull/531.
@RackHD/corecommitters @panpan0000 @iceiilin

make option downloadUrl to use FULL PATH

---

lib/graphs/switch-discovery-post-sku-hooks-graph.js

Signed-off-by: Xuebin He <xuebin.he@emc.com>

Added 'node-discovery-alert' to Switch Discovery graph

---

spec/lib/task-runner-spec.js

Resolves https://github.com/RackHD/RackHD/issues/351
The issue with this test is that the Rx take operator will limit the number of times the `subscribe` callback is called, but not the number of times the methods in the observable pipeline are called, and the test checks the callcount of a stub called in the pipeline. The reason we see the race condition is sometimes the test completes the callcount check fast enough before the next iteration of the 1ms interval we use, and sometimes it doesn't
To understand the Rx behavior, consider the difference between this code:
```
var run = true;
Rx.Observable.interval(1)
.takeWhile(function() {
return run;
})
.tap(function() {
console.log('tap');
})
.subscribe(
function() { run = false; },
function() {},
function() { console.log('complete'); }
); …
```

Fix periodic race condition in task runner heartbeat test

---

lib/graphs/docker-ps-graph.js
lib/graphs/docker-restart-graph.js
lib/graphs/docker-run-graph.js
lib/graphs/docker-service-graph.js
lib/graphs/docker-start-graph.js
lib/graphs/docker-stop-graph.js

Requires `Job.Docker` and `Job.Docker.Reconciler` from: https://github.com/RackHD/on-tasks/pull/296
If you have docker installed and running with RackHD. Create a `local-docker` node with the following structure:
``` json
{
"name": "local-docker",
"type": "compute",
"docker": {
"hostOptions": {
"ca": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n",
"cert": "-----BEGIN CERTIFICATE-----\n...\n-----END CERTIFICATE-----\n",
"host": "127.0.0.1",
"key": "-----BEGIN RSA PRIVATE KEY-----\n...\n-----END RSA PRIVATE KEY-----\n",
"port": 2376,
"protocol": "https"
}
}
}
```
This node will work when running the docker graphs.

Adds docker graphs for listing, running, and stopping containers.

---

lib/graphs/discovery-graph.js

- Make set obm settings optional and configurable
-  by adding option obmOption: true in rackhd config file

Add set-bmc task to Discovery

---

lib/task-runner.js
spec/lib/task-runner-spec.js

Jenkins depends on: https://github.com/RackHD/on-core/pull/227, https://github.com/RackHD/on-http/pull/523, https://github.com/RackHD/on-core/pull/227, https://github.com/RackHD/on-tasks/pull/370
This PR is to remove unecessary graphId in task start/finish progress event.

Remove unecessary graphId info for progress

---

lib/task-graph-runner.js

All index settings will be moved into model, see PR: https://github.com/RackHD/on-core/pull/226
The PR is to remove the index setting in graph runner to avoid the conflict.
@sunnyqianzhang @iceiilin @cgx027 
jenkins: depends on https://github.com/RackHD/on-core/pull/226

remove setIndexes to avoid conflict with Model

---

lib/service-graph.js
spec/lib/service-graph-spec.js

It is found on Jenkins continues test that sometimes on-taskgraph abnormally exits right after starting (about 1 times per day). The error msg is
```
12:52:27 PM graph.1 |  Request Timed Out (on.task-graph-runner:methods.cancelTaskGraph:Object).
12:52:27 PM graph.1 |  RequestTimedOutError: Request Timed Out (on.task-graph-runner:methods.cancelTaskGraph:Object).
12:52:27 PM graph.1 |      at null.<anonymous> (/home/vagrant/src/on-taskgraph/node_modules/on-core/lib/common/messenger.js:361:17)
12:52:27 PM graph.1 |      at Timer.listOnTimeout (timers.js:92:15)
12:52:27 PM graph.1 Exited Abnormally
```
It happened only below two conditions exist at the same time:
1. service graph (poller workflow) in mongoDB is different from current code, so that cancelTaskGraph needs to be called right …

add timeout value for cancelTaskGraph

---

lib/graphs/discovery-sku-graph.js

- In the future, the same option can be used for other node types
- nodes types like switch, PDU and  redfish discovery

Add an option to make pollers creation on compute node optional

---

lib/graphs/install-windows-server2012-graph.js

Actually this file change is just want to make this unit-test ( https://github.com/yyscamper/on-taskgraph/blob/master/spec/lib/graph-library-spec.js#L50 ) happy after task-schema refactor, in the long run, this unit-test need be refactored as well.
@RackHD/corecommitters @iceiilin @cgx027 @pengz1 @lanchongyizu @tannoa2 @amymullins 
jenkins: depends on https://github.com/RackHD/on-core/pull/217, https://github.com/RackHD/on-tasks/pull/360

support install-windows graph schema, allow unit-test passes

---

Dockerfile

Fixes build failures from missing `snmp-mibs-download`
Related PR:
https://github.com/RackHD/on-taskgraph/pull/192

Adds repo for snmp-mibs-downloader

---

lib/graphs/discovery-graph.js
lib/graphs/discovery-sku-graph.js

- Migrate set bmc credentials from discovery graph to Discovery-sku-graph
in discovery graph, group label is set in bootstrap
and it overides the tasks properties
fix for : https://github.com/RackHD/RackHD/issues/602
depends on : https://github.com/RackHD/on-http/pull/578

Bugfix: for set bmc credentials

---

lib/task-runner.js
lib/task-scheduler.js
spec/lib/task-runner-spec.js
spec/lib/task-scheduler-spec.js

Implement workflow level progress indicator after task level progress.
https://rackhd.atlassian.net/browse/RAC-3923
@RackHD/corecommitters @pengz1 @iceiilin

workflow level progress

---

lib/graphs/secure-erase-drive-graph.js

Jenkins depends on : https://github.com/RackHD/on-tasks/pull/414, https://github.com/RackHD/on-tasks/pull/415, https://github.com/RackHD/on-tasks/pull/408
Secure erase graph is updated based on two considerations:
1. To avoid wrong disk info input by user. If user doesn't use RackHD to do RAID operation, it might happen that user input disk device name doesn't match disk info in existing RackHD catalog. In this case secure erase workflow could erase a disk that user doesn't want to erase.
2. To add delay between OS ready and drives ready. After boot into microkernel, it takes something for OS to scan all disks in the case large quantity of disks are installed on the node. A secure erase task or drive re-cataloging tasks immediately after OS is ready may fail since only part of disks are …

 Update secure erase graph

---

lib/graphs/ucs-service-profile-discovery-graph.js
spec/lib/graphs/ucs-service-profile-discovery-graph-spec.js

depends on RackHD/on-tasks/pull/420

Add support for Cisco UCS Service Profile Discovery

---

lib/task-runner.js
spec/lib/task-runner-spec.js

part of the fix for https://rackhd.atlassian.net/browse/RAC-637 
supports https://github.com/RackHD/on-core/pull/269
@pscharla @RackHD/corecommitters 
If we couldn't get graph the task belongs to it's probably because the graphobjects collection was cleared we're not going to be able to get it, just filter the undefined.

filter the empty data when graph not found

---

lib/graphs/examples/install-chef-server-graph.js
spec/lib/graphs/install-chef-server-graph-spec.js

work in progress for part of https://rackhd.atlassian.net/browse/RI-136
This graph can install and prepare a chef server on a node and subsequently another graph can be run w/ the proper credentials to install the chef client on other nodes and register them with the server. However, at the moment there's not a great place to put the various keys created during the chef-server process so the key-fetching portion isn't automated and if we're going to continue integrating with other services that want some key(s) to be associated with a node it might be a good idea to talk about some kind of database or other encrypted key storage/fetching.
@pscharla @RackHD/corecommitters

added chef server install graph

---

debian/on-taskgraph.install

https://rackhd.atlassian.net/browse/RAC-4863
root cause
https://github.com/RackHD/on-taskgraph/commit/7bfecfe13f0a4fb254333ad59c3826c10a01bbfb
This commit import 
```
require('./api/rpc/index.js'),
```
and other ./api dependency.
But 
```
node_modules /var/renasar/on-taskgraph
lib /var/renasar/on-taskgraph
index.js /var/renasar/on-taskgraph
commitstring.txt /var/renasar/on-taskgraph
```
doesn't contain ./api directory.
@PengTian0 @panpan0000

add api directory in deb

---

Dockerfile
index.js

- ignore-scripts flag applies to all the installed packages.
In this case , part of grps installation is to oompile C code
- requireWrapper default home directory is different in docker
using singleWrapper instead

Allow scripts to run in npm install

---

lib/graphs/secure-erase-drive-graph.js

Secure erase workflow has typo on finish-bootstrap-trigger task waitOn condition, and will return 400. This PR is to fix typo.
Related RAC:
https://rackhd.atlassian.net/browse/RAC-4762

 Fix-RAC-4762-secure-erase-workflow-issue

---

debian/on-taskgraph.install

Fix this issue in on-taskgraph deb:
```
0|on-taskg | [error] [2017-04-19T13:05:38.559Z] [on-taskgraph] [DbRenderableContent] [Server] Unable to load views from ../../data/views.
0|on-taskg |  -> /node_modules/on-core/lib/common/db-renderable-content.js:75
0|on-taskg | error: 
0|on-taskg |   cause: 
0|on-taskg |     message: ENOENT: no such file or directory, scandir '../../data/views'
0|on-taskg |     stack: 
0|on-taskg |       - Error: ENOENT: no such file or directory, scandir '../../data/views'
0|on-taskg |       -     at Error (native)
0|on-taskg |   isOperational: true
0|on-taskg |   errno:         -2
0|on-taskg |   code:          ENOENT
0|on-taskg |   syscall:       scandir
0|on-taskg |   path:          ../../data/views
```
@panpan0000 @PengTian0

include data directory to deb

---

Dockerfile

Add on-tasks files copy in docker build.
Otherwise on-taskgraph will always use the latest on-tasks.
https://rackhd.atlassian.net/browse/RAC-4956
@panpan0000 @PengTian0

bugfix: add on-tasks files copy in docker build

---

index.js

When booting on-taskgraph service, previous there is log like
```
[info] [2017-05-24T10:04:39.652Z] [on-taskgraph] [TaskGraph] [Server] Your server is listening on port %d
-> /index.js:95
[info] [2017-05-24T10:04:39.652Z] [on-taskgraph] [TaskGraph] [Server] Swagger-ui is available on http://%s:%d/docs
-> /index.js:96
...
```
This PR modifies it to 
```
[info] [2017-05-24T10:01:36.101Z] [on-taskgraph] [TaskGraph] [Server] Your server is listening on port 9005
-> /index.js:95
[info] [2017-05-24T10:01:36.101Z] [on-taskgraph] [TaskGraph] [Server] Swagger-ui is available on http://0.0.0.0:9005/docs
-> /index.js:96
```

modify log format when starting service

---

lib/graphs/run-emc-diag-graph.js

Remove legacy options in run-emc-diag-graph.js. Callback has already been replaced by notification API.

 Remove legacy callback options for run-emc-diag

---

lib/graphs/run-emc-diag-graph.js
spec/lib/graphs/run-emc-diag-graph-spec.js

Backgroup
Current run-emc-diag workflow is old and not working during our test.
Details
1. Use force pxe boot task and obm reset to make sure boot flag won't
be cleared by emc platform rebooting
2. Add more retries to accommodate emc platform long time BMC
inaccessibility
3. Add unit test for the graph.
@nortonluo @iceiilin @anhou

 Modify run-emc-diag workflow

---

lib/task-runner.js
lib/task-scheduler.js
spec/lib/task-scheduler-spec.js

**Background**
The current on-taskgraph log misses task and graph name, which makes developers hard to track workflow's actual behavior. It will be beneficial if adding their name into it. For more details, you can go to https://rackhd.atlassian.net/browse/RAC-5456
**Details**
In on-taskgraph repo, add taskName and graphName in the function taskSchedulerFactory of the file "lib/task-scheduler.js". Besides, change unit test files. The on-taskgraph repo depends on the on-core and on-tasks repo.
Jenkins depends on: https://github.com/RackHD/on-core/pull/285, https://github.com/RackHD/on-tasks/pull/482
**TestDone**
test it successfully on ubuntu 14.04.exsi vm
**Reviewer**
@iceiilin @pengz1

[RAC-5456]add taskName and graphName into on-taskgraph log 

---

lib/graphs/dell-racadm-get-firmware-list-graph.js
lib/graphs/dell-racadm-update-firmware-graph.js

Add a capability to set updateExistingCatalog Flag to update existing catalog
instead of creating a fresh catalog each time
Add the Flag in Racadm Get Firmware list Catalog workflow(in case this graph
is run separately from Firmware Upgrade graph)

Add Racadm Get Firmware list catalog Task into Update firmware Workflow

---

lib/graphs/dell-perccli-create-megaraid-graph.js

Signed-off-by: Kranti Uppala <kranti.uppala@emc.com>
Enhance the existing workflows that meets CPSD's FRU replacement guidelines. Works on Quanta and Dell nodes with appropriate payload.
Example payload for quanta:
{
"options": {
"config-raid":{
"ssdStoragePoolArr":[],
"ssdCacheCadeArr":[
{
"enclosure": 252,
"type": "raid0",
"drives":"[0]"
}
],
"controller": 0,
"path":"/opt/MegaRAID/storcli/storcli64",
"hddArr":[
{
"enclosure": 252,
"type": "raid0",
"drives":"[1]"
},
{
"enclosure": 252,
"type": "raid1",
"drives":"[4,5]"
}
]
}
}
}

RackHD support to configure RAID on Dell 730 and Quanta

---

lib/task-scheduler.js

The root cause is, the node info is passed as an object instead of a string to the log, introducing the mess code. Change the type to string to fix this issue. @iceiilin @pengz1 @anhou 
1. Before code change, the node report mess information:
(1.1) For successful task graphs:
[TaskGraph.TaskScheduler] [Server] Graph finished
-> /lib/task-scheduler.js:527
instanceId:  03be7cf9-803b-41e9-b680-0a421899a7d6
_status:     succeeded
node:
_bsontype: ObjectID
id:
"""
YP½^\^P"H4
sE<97>
"""
schedulerId: a6d8e8cc-077a-4cf6-8445-2b2aaa161914
(1.2)For failed task graphs:
[ debug  ] [2017-08-15T08:32:07.214Z] [ec28ce] Graph finished
0|on-taskg |  -> /lib/task-scheduler.js:545
0|on-taskg | _id:                                             ==>the '_id' is a messy
0|on-taskg |   _bsontype: ObjectID …

Fix messy code in on-taskgraph.log

---

lib/task-scheduler.js

Before code change, when a taskgraph failed, it will first publish the graph finished event, and then update the taskgraph status. The issue it introduced is that: for the published graph, the status is not yet up-to-date.
The code change is to fix the problem: when a graph failed, change the graph status before publishing the graph finished event.
@pengz1 @iceiilin @lanchongyizu 
Note this code review and the other unmerged code review all changed the file lib/task-schedule.js, whichever one is merged first, the other two need rebase.
https://github.com/RackHD/on-taskgraph/pull/
https://github.com/RackHD/on-taskgraph/pull/230

To updte the failed graph status before pulbishing graph fail

---

spec/lib/services/workflow-api-service-spec.js

jenkins: depends on https://github.com/RackHD/on-core/pull/296
The error found in continuous-integration/travis-ci/pr is expected and could be ignore. When pulling the two dependent PR down and run locally, the issue doesn't exists

Fix unit test error caused by modification on on-core

---

lib/services/profile-api-service.js
lib/services/swagger-api-service.js
spec/lib/services/profile-api-service-spec.js

Fix https://rackhd.atlassian.net/browse/RAC-5768
The solution is remove lookup for macAddress when call /profiles?macs&&ips.
This is a copy of https://github.com/RackHD/on-http/pull/764

remove lookup for macAddress when call /profiles?macs&&ips

---

lib/task-runner.js
lib/task-scheduler.js

The original issue is that  graph progress is incorrect when graph failed, timeout or cancelled.
The root cause is that the method `tap` in Rxjs is not waited to finish, and the data flowing into tap is modified by later stream operation.
The solution is `cloneDeep` the `object` to be published.
Recently, https://github.com/RackHD/on-taskgraph/pull/278 has `cloneDeeped` the `graph`, so the problem has been solved in fact. So this updated PR is to `cloneDeep` the remain `objects` to be published.
@RackHD/corecommitters @pengz1 @iceiilin

Fix: graph progress is incorrect when graph failed, timeout or cancelled

---

data/templates/set_interfaces.py

@keedya @abdelazizRaji
Moved this fix from on-http to on-taskgraph.  Original PR https://github.com/RackHD/on-http/pull/781

RAC-6183 set_interfaces.py should skip virutal interfaces.

---

lib/graphs/dell-wsman-update-systemcomponents-graph.js

Add new smi-service-dell-server-configuration-profile updateComponents
API forceUpdate parameter to Graph.Dell.Wsman.UpdateSystemComponents.
When forceUpdate is set to true it allows the service to set attribute
values that are normally commented out in the exported SCP file
(i.e. the file that can be obtained by running
Graph.Dell.Wsman.Export.SCP). Examples of commented out attributes are
the BIOS boot sequence and hard drive sequence. When set to false (the
default and original UpdateSysystemComponetns behavior) those values
are silently discarded.
The forceUpdate flag was added in
smi-service-dell-server-configuration-profile [PR #16][1].
[1]: https://github.com/RackHD/smi-service-dell-server-configuration-profile/pull/16

Add forceUpdate option to UpdateSystemComponents

---

lib/graphs/examples/iPDU-firmware-update-by-sftp-graph.js
spec/lib/graphs/iPDU-firmware-update-by-sftp-graph-spec.js

In order to support the switch iPDU of ServerTech.  We use the 'CWG-16H2C454' model PDU to test.
The final solution is "SFTP Client put". RackHD provide a workflow to update iPDU firmware, named 'Graph.SftpOperation'.
- Relate PR : [on-tasks-536](https://github.com/RackHD/on-tasks/pull/536)
We can add a firmware update workflow by command: 
```
curl -X POST -H 'Content-Type: application/json' localhost:8080/api/2.0/nodes/{nodeID}/workflows -d '{
"name": "Graph.SftpOperation",
"options": {
"defaults": {
"isPDU": "true",
"fileSource": "{localFile}",
"fileDestination": "{remoteFile}"
}
}
} ' |jq '.' | grep 'instanceId'
```
@panpan0000 @anhou @pengz1

[RAC-6339] iPDU firmware update workflow define.

---

lib/graphs/dell-wsman-configure-bios-graph.js

**Background**
Based on the preceding work (  RAC-6265 DONE  ),  the configBios workflow parameters need to be refined. The "scheduledStartTime" and "utilTime" parameter will be hiden for users.  The schema will be changed.
depends on:https://github.com/RackHD/on-tasks/pull/547
**Reviewers**
@nortonluo @lanchongyizu @AlaricChan @anhou

[RAC-6433] Refine workflow parameters for WSMAN based config BIOS

---

lib/graphs/dell-wsman-update-firmware-graph.js

Background
The original WSMAN based job is out of date after SMI service updated its input parameters. And also it is lack of unit test and option schema check. Currently we refine all WSMAN implementation and aimed to integrate SMI service with RackHD and replace the RACADM. We refined the WSMAN work job arch. Now it use the new common WSMAN base job as base classs and WSMAN tool as util to send out request to SMI service. The parameters used in old wsman taskgraph are obsolete now.
Detail
Remove obsolete parameters in firmware update graph.
Test Result
Tested pass on Dell R730 server.
Review: @yaolingling @anhou @lanchongyizu @AlaricChan

Remove obsolete parameter after WSMAN control job refine

---

spec/lib/services/templates-api-service-spec.js
spec/lib/task-runner-spec.js
spec/lib/task-scheduler-spec.js

RAC:  [https://rackhd.atlassian.net/browse/RAC-5743](https://rackhd.atlassian.net/browse/RAC-5743)
----
Paired with @PengTian0 
Using both `return promise` and `done()` in async unit test case will cause following error:
`Resolution method is overspecified. Specify a callback *or* return a Promise; not both.`
According to Mocha's [official site](http://mochajs.org/):
`In Mocha v3.0.0 and newer, returning a Promise and calling done() will result in an exception`
**Solution**
----
Only call done() instead of return a promise in all async unit test cases.
@PengTian0 @pengz1 @anhou @iceiilin @bbcyyb

Unit test fix for mocha update

---

package.json
spec/lib/task-scheduler-spec.js

**Background**
----
With mocha(>=3.0) unit test can not exit properly if any services or threads like socket are not closed.
**SEE**.[https://github.com/mochajs/mocha/issues/3044](https://github.com/mochajs/mocha/issues/3044)
[https://rackhd.atlassian.net/browse/RAC-5743](https://rackhd.atlassian.net/browse/RAC-5743)
**Detail**
----
In `task-scheduler-spec.js` taskScheduler service started but not stoped, this cause mocha hanging there, to fix this, `taskScheduler.stop()` needed.
@iceiilin @anhou @pengz1 @bbcyyb @PengTian0

Fix mocha not exit bug

---

lib/graphs/dell-wsman-get-systemcomponents-catalog-graph.js

The original get system config components task is not working. it used share folder to handle .xml exchange file but it doesn't accept share folder username &password.
It only do catalog create. When there is already catalogs in db, it will get problem.
Also latest data format update in SMI service response make the result data incorrect.
Add share folder setting parameters. It should be still compatible with original call method.
Change catalog create method. Only create if there is no such record in db. If found similar on, it only do update.
Fixed the json format transfer bug.
Add task schema
Add unit test for all the jobs.
@lanchongyizu @yaolingling @AlaricChan @anhou @leoyjchang
It depends on:RackHD/on-tasks#564

RAC-6480 Refine get system config catalog graph parameters

---

data/templates/install-ubuntu/ubuntu-preseed
data/templates/install-ubuntu/ubuntu.rackhdcallback

****Background:**** 
----
Workflow cannot finish after successfully installed ubuntu16.04, this is because callback script in 16.04 cannot be executed during the init boot.
Detail:
----
Ubuntu 16.04 uses _**systemd**_ to start the boot scripts not _**init**_ in 14.04, but scripts in **_/init.d_** can still work in 16.04 because 16.04 uses _**systemd-sysv-generator**_ to generate services for each script in /init.d(purpose of backward compatibility). And there is no runlevel concept in 16.04, boot facilities should run in parallel, if sequential is required, use  **_LSB comment header_** in scripts.
For more detail about LSB please see [https://wiki.debian.org/LSBInitScripts](https://wiki.debian.org/LSBInitScripts)
@pengz1 @anhou @PengTian0 @Ara4Sh

[RAC-6385] Fix ubuntu16.04 support

---

data/templates/esx-ks

Add `clearDisk` option to Graph.InstallESXi to allow better control
over the `clearpart` command which is used to clear disk partition
tables during OS install. Valid `clearDisk` values are:
- `null` or unspecified: only clear the partition table on the disk
the OS is being installed to. This is the same behavior as prior to
this change.
- `alldrives`: clear the partition table on all drives.
- or a disk path that the OS can recognize.
depends on: https://github.com/RackHD/on-tasks/pull/532

Add ESXi installer option for clearing disk partitions

---

data/templates/install-ubuntu/ubuntu-netplan-interfaces
data/templates/install-ubuntu/ubuntu-preseed

This change introduces a new template for Ubuntu 17.10's use of netplan instead of
the usual /etc/network/interfaces.  If the version is artful, the netplan yaml
is downloaded.
Signed-off-by: mbeierl <mark.beierl@dell.com>

Adds support for Netplan

---

lib/graphs/run-rest-command-graph.js

Adding graph to run REST commands on external hosts, currently for used with redfish discovery.
************
Part of Changes in on-core, on-http, on-tasks, on-taskgraph
The combination of these changes is to fully implement redfish device discovery. This includes the fillowing items:
1) The implementation of unique device identifiers in place of the RackHD GUID identifers.
a) These ids provide the user the ability to know which node they are looking at. This is usefull for
aggregation.
b) All RackHD Redfish calls can use either the new id or the original RackHD GUID. The RackHD api still can
only use the GUID.
c) Currently this id is made with a combination of the serial number and sku from the redfish discovery.
2) Creation of redfish and redfishManager node types.
a) redfish nodes are …

Adding redfish node for chassis/system combo

---

data/templates/cloud-config.yaml
lib/graphs/bootstrap-decommission-node-graph.js
lib/graphs/bootstrap-decommission-node-test-graph.js
lib/graphs/bootstrap-megaraid-config-graph.js
lib/graphs/create-megaraid-graph.js
lib/graphs/delete-megaraid-graph.js
lib/graphs/dell-perccli-create-megaraid-graph.js
lib/graphs/dell-perccli-megaraid-catalog-graph.js
lib/graphs/dell-racadm-update-firmware-graph.js
lib/graphs/discovery-redfish-system-graph.js
lib/graphs/flash-megaraid-controller-graph.js
lib/graphs/flash-quanta-all-graph.js
lib/graphs/flash-quanta-bios-graph.js
lib/graphs/flash-quanta-bmc-graph.js
lib/graphs/flash-quanta-megaraid-graph.js
lib/graphs/intel-flashupdt-catalog-graph.js
lib/graphs/quanta-storcli-megaraid-catalog-graph.js
lib/graphs/secure-erase-drive-graph.js
lib/graphs/shell-command-graph.js
lib/graphs/write-quanta-bios-nvram-graph.js

**Background**
Currently, we have replaced old microkernel with RancherOS, but we only use `bootstrap-rancher` to run discovery workflow. Here is to replace all other `bootstrap-ubuntu` with `bootstrap-rancher`. 
This is related with https://rackhd.atlassian.net/browse/RAC-6581
**Done**
* Replace all other `bootstrap-ubuntu` with `bootstrap-rancher`
* Replace `overlayfsFile` with `dockerFile`
depends on: https://github.com/RackHD/on-tasks/pull/577
@RackHD/corecommitters @keedya

Replace bootstrap-ubuntu with bootstrap-rancher

---

data/templates/ansible-external-inventory.js
data/templates/autounattend_windows_2012_r2_SMC_6028U-TR4+.xml
data/templates/autounattend_windows_2012_r2_unknown.xml
data/templates/autounattend_windows_2012_r2_vmware.xml
data/templates/centos-ks
data/templates/esx-ks
data/templates/install-debian/debian-preseed
data/templates/install-debian/post-install-debian.sh
data/templates/install-photon/photon-os-ks
data/templates/install-photon/post-install-photon.sh
data/templates/pxe-cloud-config.yml
data/templates/remove_bmc_credentials.sh
data/templates/secure_erase.py
data/templates/set_bmc_credentials.sh
data/templates/suse-autoinst.xml
data/templates/unattend_server2012.xml
data/templates/winpe-kickstart.ps1

**Background**
Users need to include special character in password, such as `&`. But password is escaped in the templates currently, e.g. `&` is escaped into `&amp;`.
https://rackhd.atlassian.net/browse/RAC-6602
**Done**
* Replace `<%=` with `<%-` for password.
@RackHD/corecommitters @panpan0000 @nortonluo

Don't escape password in templates

---

lib/graphs/esxcli-driver-version-commands-graph.js
lib/graphs/examples/install-chef-graph.js
lib/graphs/examples/install-chef-server-graph.js

**Background**
This is to fix "No parser" issue:
```
No parser exists for command sudo ./megaraid-config.sh
No parser exists for command sudo python set_interfaces.py 
No parser exists for command sudo ipmitool chassis bootdev pxe
```
https://rackhd.atlassian.net/browse/RAC-6579
**Done**
* Separate ssh-job into ssh-command and ssh-catalog
depends on: https://github.com/RackHD/on-tasks/pull/580
@RackHD/corecommitters @pengz1 @nortonluo

Separate ssh-job into ssh-command and ssh-catalog

---

data/templates/centos-ks

Added support for creating Tagged Bond Interface. This will enable support for having one or multiple tagged sub-interfaces created along with the LACP bond interface

RHEL 7 Bond VLAN interface support

---

data/profiles/install-debian.ipxe

Fixing kernel panic error during EFI boot on debian and ubuntu installation . 
`kernel panic not syncing vfs unable to mount root fs on unknown-block (1,0)`

Fix Debian/Ubuntu kernel panic on EFI

---

data/templates/cloud-config.yaml

My inspur server needs to modprobe ipmi_si during discovery.

modprobe ipmi_si in rancher os

---

lib/graphs/dell-wsman-post-discovery-graph.js

The node discovered by WSMAN discovery workflow have no mac lookup entry associated with it. This is because the traditional micro kernel discovery way have a step to update lookup table but WSMAN do not.
Add a task to use the MAC address in node catalog to update lookup table. This task will be execute in the post WSMAN discovery workflow after get WSMAN inventory.
depends on:https://github.com/RackHD/on-tasks/pull/587
@lanchongyizu @pengz1 @iceiilin @markbeierl

[RAC-6682] Add lookup update in post WSMAN device discovery

---

data/profiles/dell-onie.sh
data/templates/dell-catalog-sysinfo.sh
lib/graphs/dell-switch-discovery-graph.js
lib/services/profile-api-service.js

- It uses Onie discovery to load a shell script (taskrunner)
- Currently we collect version and serial nb
- To enable this feature, the user has to configure the dhcp server as follow:
`
class "dellswitch" {
match if substring (hardware, 1, 6) = 4c:76:25:f6:64:00;
}
pool {
allow members of "dellswitch";
range 172.31.128.241 172.31.128.250;
option default-url = "http://172.31.128.1:9030/api/current/profiles/switch/dell";
}`
Next step : 
- Adding a script to load os image using onie discovery
- Catalog:
`[
{
"id": "8c5128cc-6075-44b6-acc5-b2936b0edc73",
"node": "/api/2.0/nodes/5acf85bae595224a77b7f5da",
"createdAt": "2018-04-12T16:13:48.885Z",
"updatedAt": "2018-04-12T16:13:48.885Z",
"source": "sysinfo",
"data": {
"version": "3.25.1.2",
"serialNb": "CN0WKFYN7793164F0017"
}
}
]`
- Created …

Adding switch deiscovery for Dell s6000

---

data/profiles/dell-bmp.sh
data/templates/dell-switch-basic-config.exp
data/templates/dell-switch-catalog.sh
data/templates/dell-switch-onie-catalog.sh
lib/graphs/dell-onie-switch-discovery-graph.js
lib/graphs/dell-switch-config-graph.js
lib/services/profile-api-service.js
spec/lib/services/profile-api-service-spec.js

- Assuming 172.31.128.0/22 is our southbound subnet
- Port 9030 is taskgraph listener
- Port 9090 is http server
`
class "dellswitch" {
match if substring (hardware, 1, 6) = 4c:76:25:f6:64:02;
}
class "dellonie" {
match if substring (hardware, 1, 6) = 4c:76:25:f6:64:00;
}
subnet 172.31.128.0 netmask 255.255.255.0 {
pool{
allow members of "dellswitch";
range 172.31.128.4 172.31.128.10;
option configfile = "http://172.31.128.1:9090/dell-bmp-entrypoint.exp";
}
pool{
allow members of "dellonie";
range 172.31.128.241 172.31.128.250;
option default-url = "http://172.31.128.1:9030/api/current/profiles/switch/onie";
}
}
`
- Create a new file called dell-bmp-entrypoint.exp
`
#!/usr/bin/expect
#/DELL-FORCE10
##Global Variable
############FUNCTIONS############
proc print_output {str} {
puts $str
} …

Add support for dell switch discoveryand add basic configuration 

---

lib/graphs/bootstrap-megaraid-config-graph.js
lib/graphs/dell-perccli-create-megaraid-graph.js

After creating raid successfully, "driveid" catalog and "lsall" catalog needs to refresh.

add refresh-catalog tasks after creating raid successfully

---

data/templates/unattend_server2012.xml

Windows installer throws error about failure to handle unsttend.xml when specifying more than one network device.
Change the order in the template from
```
<component>
<Interfaces>
<Interface></Interface>
</Interfaces>
<Interfaces>
<Interface></Interface>
</Interfaces>
</component>
```
into 
```
<component>
<Interfaces>
<Interface></Interface>
<Interface></Interface>
</Interfaces>
</component>
```
The latter is the same with https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-tcpip-interfaces.

Error analyzing Windows unattend file when specifying two network devices

---

lib/graphs/bootstrap-ubuntu-graph.js
lib/graphs/brocade-switch-discovery-graph.js
lib/graphs/discovery-mgmtsku-graph.js
lib/graphs/discovery-sku-orig-graph.js
lib/graphs/flash-quanta-all-graph.js
lib/graphs/pdu-discovery-graph.js
lib/graphs/rancher-discovery-graph.js

*Background*
It has been found during web ui development that some graphs have extra space in their friendlyname. After further screening, I also found some typo in some graph's friendlyname.  This is not a good style and we need to fix them all.
@lanchongyizu @pengz1 @yaolingling @iceiilin @mcgG @AlaricChan

[RAC-6753]Correct several taskgraph's friendlyName

---

lib/graphs/rancher-catalog-graph.js
lib/graphs/redfish-discovery-ip-range-graph.js
lib/services/profile-api-service.js
spec/lib/graphs/rancher-catalog-graph-spec.js

Here is the scenario we are trying to accomplish (The user already has
the nodes powered on)
1. knowing the Idrac IP, we want to run the redfish discovery workflow.
This step will create the obm and catalog redfish. We can add a step
here to get the host mac addresses and populate the lookup table.
2. Since the node is discovered a pxe discovery shouldn't trigger
automatically but we should have a pxe discovery workflow that the user
can run against a discovered node to populate the catalog with pxe
cataloging data.
https://rackhd.atlassian.net/browse/RAC-6777
depends on: https://github.com/RackHD/on-tasks/pull/596
@keedya @iceiilin @pengz1

Add update-lookups for redfish range discovery
