RackHD/on-taskgraph

lib/graphs/discovery-mgmt-graph.js

Included local dmidecode catalog to graph
@RackHD/corecommitters @RackHD/rackhd_dev

VEY-204: Add local lldp catalog task to mgmt server discovery graph

---

lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-rhel-graph.js
lib/scheduler.js

Recreated PRs for ODR-273 fix on 1.0.0 branch.  Needed for 1.0.5 release.

Scheduler: call taskProtocol.cancel with timeout error/message on timout

---

lib/graphs/discovery-graph.js

It is the fix of ODR-338, https://hwjiraprd01.corp.emc.com/browse/ODR-338
Added driveId catalog into discovery workflow.
Related PRs:
https://github.com/RackHD/on-tasks/pull/86
https://github.com/RackHD/on-http/pull/60

Added drive id catalog into discovery workflow

---

lib/graphs/discovery-graph.js

Add drive ID catalog task in discovery workflow.

Add drive id catalog task in discovery workflow

---

.bintray.json
.travis.yml

Deploy debian packages to bintray

---

debian/control

@RackHD/corecommitters @RackHD/rackhd_dev

Move depends and description to single line

---

index.js
package.json
spec/lib/loader-spec.js
spec/lib/service-graph-spec.js
spec/lib/task-graph-spec.js
spec/lib/task-graph-subscriptions-spec.js

Depends on https://github.com/RackHD/on-core/pull/61
Tests should fail until `on-core` PR is merged.

Upgrade lodash to version 3.10.1

---

README.md

Added node inspector steps to README

Adds node-inspector instructions to README

---

debian/control

Reverts RackHD/on-taskgraph#45

Revert "Specify version 1.8.13-1 for ipmitool package"

---

lib/graphs/discovery-refresh-graph.js

(cherry picked from commit 8dd0c7c7716dde6efa12b25f5b4cd4fef04c6710)

ON-2719 Adds discovery-refresh-graph.js

---

lib/graphs/discovery-refresh-graph.js

Updated discovery-refresh-graphs.js to use sku discovery tasks instead of just discovery.

ODR-547 Updated discovery-refresh-graphs.js to use sku discovery

---

lib/graphs/dell-racadm-set-bios-graph.js
spec/lib/graphs/dell-racadm-set-bios-graph-spec.js

Add a workflow to set bios with dell racadm tool

Add a workflow to set bios with dell racadm tool

---

lib/graphs/redfish-discovery-graph.js
lib/graphs/redfish-reset-actions-graph.js
spec/lib/graphs/redfish-discovery-graph-spec.js
spec/lib/graphs/redfish-reset-actions-graph-spec.js

@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya

Add redfish discovery and action reset graph

---

lib/graphs/discovery-mgmtsku-graph.js
lib/graphs/discovery-sku-graph.js
lib/graphs/generate-tag.graph.js
spec/lib/graphs/generate-tag.graph.js

@RackHD/corecommitters @uppalk1 @keedya @tannoa2 
Depends on https://github.com/RackHD/on-tasks/pull/124, https://github.com/RackHD/on-core/pull/88

Add node tagging tasks to graphs

---

lib/graphs/discovery-refresh-delayed-graph.js
lib/graphs/discovery-refresh-graph.js
lib/graphs/discovery-refresh-immediate-graph.js

master pull request for ODR-547 work.

Odr 547 master

---

lib/graphs/dell-racadm-get-bios-graph.js
lib/graphs/dell-racadm-update-firmware-graph.js
spec/lib/graphs/dell-racadm-get-bios-graph-spec.js
spec/lib/graphs/dell-racadm-update-firmware-graph-spec.js

With Racadm tool
This code review is link with the code change on on-tasks:
RackHD/on-tasks#133

Add workflow for getting bios and update firmware

---

Dockerfile
docker_entry.sh

Remove dhcp server, and force copy node_modules.
Related to: https://github.com/RackHD/RackHD/pull/109

Dockerfile changes.

---

lib/graphs/install-suse-graph.js
spec/lib/graphs/install-suse-graph-spec.js

related PR
https://github.com/RackHD/on-http/pull/174
https://github.com/RackHD/on-tasks/pull/140

Add openSUSE/SLES bootstrap graph

---

lib/graphs/create-redfish-poller-graph.js
lib/graphs/discovery-sku-graph.js
lib/graphs/poller-service-graph.js
lib/graphs/redfish-discovery-graph.js

Adds create chassis poller graph.
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya 
For PR https://github.com/RackHD/on-tasks/pull/139

Add Redfish Chassis poller graph

---

lib/graphs/discovery-graph.js
lib/graphs/set-bmc-credentials-graph.js
spec/lib/graphs/set-bmc-credentials-graph-spec.js

One task is to run a template that creates a BMC username and password. The second task updates the mongoDB with new obmSettings.

Created a graph that sets up the BMC credentials

---

lib/graphs/create-redfish-chassis-poller-graph.js
lib/graphs/create-redfish-systems-poller-graph.js
lib/graphs/emc-compose-system-graph.js
lib/graphs/emc-redfish-discovery-graph.js
spec/lib/graphs/create-redfish-chassis-poller-graph-spec.js
spec/lib/graphs/create-redfish-systems-poller-graph-spec.js
spec/lib/graphs/emc-compose-system-graph-spec.js
spec/lib/graphs/emc-redfish-discovery-graph.js

- Redfish System and Chassis pollers
- Platform-A Catalog and Compose
@RackHD/corecommitters @zyoung51 @geoff-reid @uppalk1  @tannoa2 @keedya 
Depends on https://github.com/RackHD/on-tasks/pull/145

Add Emc Oem Catalog, Poller and Compose graph

---

lib/graphs/create-redfish-managers-poller-graph.js

@RackHD/corecommitters @zyoung51 @geoff-reid @tannoa2 @keedya @uppalk1
Dependency: https://github.com/RackHD/on-tasks/pull/155

Add Redfish Managers LogServices poller create graph

---

lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-ubuntu-graph.js

@RackHD/corecommitters @heckj @VulpesArtificem

Add validate ssh task to OS install graphs

---

lib/graphs/create-emc-fabric-service-poller-graph.js
spec/lib/graphs/create-emc-fabric-service-poller-graph-spec.js

@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya @geoff-reid

Adds Emc OEM FabricService Poller Workflow

---

lib/graphs/redfish-discovery-graph.js

@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya @geoff-reid

[redfish] Create default Redfish pollers and EMC OEM pollers in discovery

---

lib/graphs/arp-poller-service-graph.js
lib/graphs/isc-dhcp-poller-service-graph.js

@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya @geoff-reid 
Dependent PR https://github.com/RackHD/on-tasks/pull/182

Add ARP Poller Graph

---

lib/graphs/secure-erase-drive-graph.js
spec/lib/graphs/secure-erase-drive-graph-spec.js

Use drive secure erase task to form the corresponding workflow.
Related PR:
https://github.com/RackHD/on-tasks/pull/225

Add a workflow for securing erase drive

---

lib/graphs/redfish-discovery-graph.js

* Added elements.thermal command under options

PlatformA VM- support Thermal pollers for OEM element resources

---

lib/graphs/bootstrap-decommission-node-graph.js
spec/lib/graphs/bootstrap-bmc-credentials-remove-graph-spec.js
spec/lib/graphs/bootstrap-decommission-node-graph-spec.js

@jlongever @benbp @zyoung51 
- Remove BMC users
- Allow user to select between secure erase or run  DD shell command on the node

Decommission graph

---

lib/graphs/switch-discovery-graph.js

depends On: https://github.com/RackHD/on-tasks/pull/241
@RackHD/corecommitters @jlongever @tannoa2 @zyoung51 @uppalk1

Add switch-node-relations task to switch discovery graph

---

lib/graphs/dell-racadm-disable-vtx-graph.js
lib/graphs/dell-racadm-enable-vtx-graph.js
spec/lib/graphs/dell-racadm-disable-vtx-graph-spec.js
spec/lib/graphs/dell-racadm-enable-vtx-graph-spec.js

This PR is to create workflows for setting dell server bios vtx attributes.

Create workflow to switch dell server bios VT-x attribute

---

spec/lib/graph-library-spec.js

Fixes a minor test mocking issue caused by https://github.com/RackHD/on-tasks/pull/238
@RackHD/corecommitters @tldavies

Stub env collection in graph validation test

---

lib/graphs/install-esx-graph.js

Fixes: https://github.com/RackHD/RackHD/issues/258
Requires: https://github.com/RackHD/on-tasks/pull/234

Changes $taskTimeout to _taskTimeout

---

lib/graphs/run-emc-diag-graph.js

@RackHD/corecommitters @tannoa2 @uppalk1 @keedya @zyoung51 
Dependency on PR https://github.com/RackHD/on-http/pull/345 and  RackHD/on-tasks#256

Create OEM diag workflow

---

lib/graphs/switch-discovery-graph.js

Adding snmp txrx counters to default poller graph
This is depend on https://github.com/RackHD/on-tasks/pull/246

Adding switich telemtry to default poller 

---

lib/graphs/install-centos-graph.js

@RackHD/corecommitters @jlongever @zyoung51 @keedya @uppalk1 @amymullins

Fix a timeout issue with the centOS install graph

---

lib/graphs/install-esx-graph.js

resolve RackHD/RackHD#218
require https://github.com/RackHD/on-tasks/pull/276 

Change Graph.InstallEsx to Graph.InstallESXi

---

lib/graphs/install-photon-graph.js
spec/lib/graphs/install-photon-graph-spec.js

Photon OS bootstrap support
This is one of three PRs for Photon OS bootstrap:
RackHD/on-tasks #275  https://github.com/RackHD/on-tasks/pull/275
RackHD/on-taskgraph #138 https://github.com/RackHD/on-taskgraph/pull/138 
RackHD/on-http #362 https://github.com/RackHD/on-http/pull/362
@RackHD/corecommitters @iceiilin @pengz1 @WangWinson

Add install Photon OS graph

---

lib/graphs/brocade-switch-discovery-graph.js

Changes related to on-http repo PR:  Brocade VDX switch integration as part of switch discovery #331 
Added default graph definition to catalog brocade switch.

Brocade VDX switch integration as part of switch discovery

---

lib/graphs/pdu-discovery-graph.js

depends on : https://github.com/RackHD/on-tasks/pull/286

Add pdu-node relation to pdu discovery graph

---

lib/graphs/discovery-redfish-system-graph.js

- Create active discovery graph for Redfish System resources.
@RackHD/corecommitters @zyoung51 @uppalk1 @tannoa2 @keedya

Add Redfish system specific discovery graph

---

README.md

updated README to show you can use 2.0 API and updated how to get active graph on a node using 2.0 API
@RackHD/corecommitters @keedya @srinia6

README 2.0 API updates

---

lib/graphs/redfish-discovery-graph.js

- Create element power poller during Redfish discovery.
- Dependent PR: https://github.com/RackHD/on-tasks/pull/301
@RackHD/corecommitters @uppalk1 @zyoung51 @tannoa2 @keedya

Create element power poller in redfish discovery

---

lib/graphs/emc-compose-system-graph.js

- Create system pollers for newly composed systems
- Dependent PR https://github.com/RackHD/on-tasks/pull/300
@RackHD/corecommitters @uppalk1 @tannoa2 @keedya @zyoung51

Create Redfish pollers in compose graph

---

lib/service-graph.js
spec/lib/service-graph-spec.js

Fixes https://github.com/RackHD/RackHD/issues/371
@RackHD/corecommitters @VulpesArtificem @rolandpoulter

Fix bug that created duplicate service graph instances

---

lib/graphs/pdu-discovery-graph.js

Add run-sku-graph task to PDU discovery

---

lib/graphs/poller-service-graph.js
lib/graphs/switch-discovery-graph.js

Add new poller to discovery graph and remove old poller

---

lib/graphs/discovery-refresh-delayed-graph.js
lib/graphs/discovery-refresh-immediate-graph.js
lib/graphs/discovery-sku-graph.js

@RackHD/corecommitters @zyoung51 @tannoa2 @uppalk1 @keedya 
Dependent PR: https://github.com/RackHD/on-tasks/pull/326

Create SEL entry poller

---

lib/graphs/install-centos-graph.js
lib/graphs/install-esx-graph.js
lib/graphs/install-photon-graph.js
lib/graphs/install-rhel-graph.js
lib/graphs/install-windows-server2012-graph.js
lib/graphs/run-emc-diag-graph.js

* replace WaitCompletionUri with WaitNotificationJob in all workflows
** Note: Graph.Run.Emc.Diag can not complete now.

Replace completionUri with notification

---

debian/on-taskgraph.init

- enable start/stop/restart and pid monitoring
- put logs in /var/log/rackhd
https://github.com/RackHD/on-http/issues/416

Better init script

---

lib/graphs/bootstrap-decommission-node-graph.js

@brianparry @jlongever @zyoung51 @uppalk1 @tannoa2

Update graph decommission nodeand fix graph bugs

---

Dockerfile

Replaces `apk` commands with `apt-get`

Updates Dockerfile to use debian wheezy

---

lib/task-scheduler.js
spec/lib/task-scheduler-spec.js

fix for https://github.com/RackHD/RackHD/issues/327
requires
https://github.com/RackHD/on-tasks/pull/344
and
https://github.com/RackHD/on-core/pull/213
@RackHD/corecommitters @pscharla

don't fail graph if ignoreFailure true

---

lib/graphs/install-esx-graph.js

* seperate static file of bootstrap and os repos from api.server into file.server
@RackHD/corecommitters @iceiilin @cgx027 @panpan0000 @benbp 
https://github.com/RackHD/on-tasks/pull/347

seperate static file of bootstrap and os repos from api.server into file.server

---

lib/graphs/install-ubuntu-graph.js

Dependency on PR https://github.com/RackHD/on-tasks/pull/366 https://github.com/RackHD/on-http/pull/510

Add callback script to ubuntu installation workflow

---

debian/on-taskgraph.init

1. This PR removed the "--force".
Because ubuntu 16.04 doesn't support the option.
2. This PR added time interval after starting and stopping service. 
Because sometimes the service won't start but will later when running the command "service start" 
@yyscamper @anhou @panpan0000

enhance the debian init script to support ubuntu 16.04

---

lib/task-runner.js
spec/lib/task-runner-spec.js

Related PRs:
https://github.com/RackHD/on-tasks/pull/364, 
RackHD/on-core#221, 
https://github.com/RackHD/on-http/pull/507
Add progress event trigger mechanism when task/workflow started/finished.

Implement progress feature 

---

Dockerfile

related PR for Vagrant: https://github.com/RackHD/on-taskgraph/pull/192
Signed-off-by: Joe Heck <heckj@mac.com>

adding MIB downloads to docker image

---

lib/graphs/discovery-graph.js

@RackHD/corecommitters @yyscamper

Rename obmOption to autoCreateObm

---

lib/graphs/bootstrap-decommission-node-graph.js

Update decommission compute node workflow

---

lib/graphs/bootstrap-decommission-node-graph.js

@RackHD/corecommitters 
this resolves https://github.com/RackHD/RackHD/issues/373
this depends on https://github.com/RackHD/on-imagebuilder/pull/56

changed decommission graph to use sgdisk

---

spec/lib/task-runner-spec.js

@brianparry @srinia6 @BillyAbildgaard

Unit test fixes

---

lib/completed-task-poller.js
lib/task-scheduler.js
spec/lib/completed-task-poller-spec.js
spec/lib/task-scheduler-spec.js

depend PR https://github.com/RackHD/on-core/pull/248

update publishGraphFinished parameters

---

lib/graphs/discovery-graph.js
lib/graphs/discovery-sku-graph.js

Fix Discovery failure introduced by adding set bmc credentials as an option

Fix Discovery graph

---

Dockerfile

source list should be added once only in on-core https://github.com/RackHD/on-core/pull/255 images and be removed here
@panpan0000 
PR merge order:
https://github.com/RackHD/on-core/pull/255 first, then after dockerhub autobuild success,
this PR should be merged.
then the next day
https://github.com/RackHD/on-build-config/pull/80 should be merged to support the daily build.

[skip ci]remove sources list actions

---

lib/services/workflow-api-service.js
spec/lib/services/workflow-api-service-spec.js

moving latest task progress into the workflow service in on-taskgraph
Merging this PR will update the following PR against master: https://github.com/RackHD/on-taskgraph/pull/215
@RackHD/veyron 
jenkins: depends on https://github.com/RackHD/on-http/pull/592

getting up to date with master

---

lib/graphs/discovery-sku-graph.js
lib/graphs/rancher-discovery-graph.js

- Allow us to use micro docker image in the active
discovery on compute nodes

Replace bootstrap ubuntu with rancherOS in discovery and Micro-docker

---

lib/graphs/discovery-sku-graph.js
lib/graphs/rancher-discovery-graph.js

This reverts commit 1e6fc7c3a91133540c92fa698703f075b4e179f2.

Revert "Replace bootstrap ubuntu with rancherOS in discovery"

---

lib/completed-task-poller.js
lib/task-runner.js
lib/task-scheduler.js
spec/lib/completed-task-poller-spec.js
spec/lib/task-runner-spec.js
spec/lib/task-scheduler-spec.js

Refactor workflow progress implementation with progress service design.
1) move publishTaskStarted of progress into Services.GraphProgress
2) move publishTaskFinished of progress into Services.GraphProgress
3) move publishGraphFinished of progress into Services.GraphProgress
This PR is related with https://rackhd.atlassian.net/browse/RAC-4390
Jenkins: depends on https://github.com/RackHD/on-core/pull/261 https://github.com/RackHD/on-tasks/pull/418 https://github.com/RackHD/on-http/pull/598
@RackHD/corecommitters @pengz1 
AMQP messages for Graph.Started Event:
```
graph.started.85f1ca29-cd2d-4160-9099-0b734b96255a
{ status: 'running' }
graph.started.information.85f1ca29-cd2d-4160-9099-0b734b96255a.58c0b2d8d3b364a1745abbbe
{ type: 'graph',
action: 'started',
typeId: …
```

Refine workflow progress

---

lib/graphs/examples/install-chef-graph.js
spec/lib/graphs/install-chef-graph-spec.js

https://rackhd.atlassian.net/browse/RAC-4146
added a graph to install, configure, and run the chef client on a node. 
@pscharla @RackHD/corecommitters @panpan0000

added chef install POC

---

lib/graphs/dell-racadm-update-firmware-graph.js

Extend existing Graph to support iDRAC Firmware Upgrade 

Extend graph to support iDRAC Firmware Upgrade

---

lib/graphs/dell-racadm-get-firmware-list-graph.js
spec/lib/graphs/dell-racadm-get-firmware-list-graph-spec.js

Unit test for /dell-racadm-get-firmware-list-graph
jenkins: depends on https://github.com/RackHD/on-tasks/pull/435

Add new workflow for Dell Racadm Get firmware catalog

---

lib/graphs/dell-perccli-megaraid-catalog-graph.js
spec/lib/graphs/dell-perccli-megaraid-catalog-graph-spec.js

jenkins: depends on RackHD/on-tasks#436

Add support for PERC cli version catalog for dell servers

---

debian/on-taskgraph.install

Detail in https://rackhd.atlassian.net/browse/RAC-4884
on-taskgraph deb can't start
Thanks to @lanchongyizu 
Reviewer: 
@brianparry  @changev @yyscamper  @anhou  @PengTian0  @lanchongyizu

RAC-4884: Add scheduler.proto into deb

---

lib/graphs/add-hotspare-graph.js
lib/graphs/add-volume-graph.js
lib/graphs/delete-volume-graph.js

on-taskgraph code additions. Includes graphs for create volume, delete
volume, and add hotspare.

on-taskgraph code

---

lib/graphs/dell-racadm-update-firmware-graph.js

- Force pxe and reboot after firmware update
- reboot the system after running catalog updates
@dalebremner @brianparry @geoff-reid @tannoa2

This is a fix for RAC-5101

---

lib/graphs/ucs-discovery-graph.js

Fix for https://rackhd.atlassian.net/browse/RAC-5116

Fix creating duplicate entries - UCS Catalog/Discovery

---

lib/graphs/bootstrap-decommission-node-test-graph.js

* Created decommission validation workflow

RAC-4819 - convert decommission nodes script to FIT

---

lib/graphs/set-idrac-ipaddress.js
spec/lib/graphs/set-idrac-ipaddress-spec.js

- using using ipmitool and microkernel post discovery phase
`{
"options": {
"ssh-to-micokernel": {
"commands": [
"sudo ipmitool lan set 1 ipsrc static",
"sudo ipmitool lan set 1 ipaddr 10.0.0.3",
"sudo ipmitool lan set 1 netmask 255.255.255.0",
"sudo ipmitool lan set 1 defgw ipaddr 10.0.0.1"
]
}
}
}`

RackHD Setting up Idrac ip

---

lib/graphs/redfish-discovery-graph.js

Signed-off-by: Billy Abildgaard <william.abildgaardjr@emc.com>
Add Redfish catalog of dell endpoint to redfish discovery graph. Depends on 
https://github.com/RackHD/on-tasks/pull/462

Add Redfish catalog of dell endpoint to redfish discovery graph

---

.travis.yml
extra/make-deb.sh

See [on-dhcp-proxy 73](https://github.com/RackHD/on-dhcp-proxy/pull/73)

[RAC-5774]add deb build in on-taskgraph's TravisCI .

---

lib/completed-task-poller.js
lib/services/workflow-api-service.js
lib/task-scheduler.js
spec/lib/completed-task-poller-spec.js
spec/lib/services/schema-api-service-spec.js
spec/lib/services/workflow-api-service-spec.js
spec/lib/task-scheduler-spec.js

1) update all that call eventsProtocol.publishGraphFinished
2) update all that call eventsProtocol.publishGraphStarted
Jenkins: depends on https://github.com/RackHD/on-core/pull/291

add graphId and graphName for event of graphStarted and graphFinished

---

lib/graphs/quanta-storcli-megaraid-catalog-graph.js
spec/lib/graphs/quanta-storcli-megaraid-catalog-graph-spec.js

Signed-off-by: Kranti Uppala <kranti.uppala@emc.com>

Create new workflow for Quanta megaraid catalog

---

debian/on-taskgraph.install

add app.js to debian package

---

Dockerfile
HWIMO-BUILD
alpha/build_deb.sh
alpha/build_deb.yml
alpha/build_docker.sh
alpha/build_docker.yml
alpha/post_build_deb.yml
alpha/post_unittest.yml
alpha/set_dependencies.sh
alpha/unittest.sh
alpha/unittest.yml

@geoff-reid @hohene @johren @srinia6

Add concourse support scripts

---

lib/graphs/dell-racadm-reset-components-graph.js
spec/lib/graphs/dell-racadm-reset-components-graph-spec.js

Paired with @patelb10 @pathakvaidehi2391 @manfrednde @jimturnquist

RAC-4910 Add Graph for /redfish/systems/indentifier/reset components

---

Dockerfile

Signed-off-by: Andre Keedy <Andre.Keedy@emc.com>
depends on: https://github.com/RackHD/on-core/pull/300

Manually add snmp

---

lib/graphs/redfish-discovery-ip-range-graph.js
lib/task-scheduler.js

Changes to support redfish cataloging of power and cooling nodes.  
@RackHD/committers @keedya

Redfish catalog

---

lib/graphs/dell-wsman-configure-bios-graph.js

Made the changes and ran the Hound checks.

DELL WSMAN Configure BIOS Task Graph.

---

lib/graphs/poller-service-graph.js
lib/graphs/ucs-catalog-graph.js
lib/graphs/ucs-discovery-graph.js
lib/graphs/ucs-poller-graph.js
spec/lib/graphs/poller-service-graph-spec.js
spec/lib/graphs/ucs-poller-graph-spec.js

RAC-6100 Add graph for ucs poller and its unit test
----
Add ucs poller to discovery graph
jenkins depends on:
https://github.com/RackHD/on-tasks/pull/515, RackHD/ucs-service#24
@iceiilin @anhou @yaolingling @pengz1 @bbcyyb

RAC-6100 Add graph for ucs poller and its unit test

---

api/rpc/index.js
api/rpc/templates.js
scheduler.proto

Added Template /DELETE support over grpc

---

lib/graphs/dell-racadm-update-firmware-graph.js

Signed-off-by: Dale Bremner <dale.bremner@dell.com>

Added download task

---

data/templates/set_bmc_credentials.sh
lib/services/swagger-api-service.js

Correct errors found in the taskgraph log

---

data/profiles/taskrunner.py
lib/services/profile-api-service.js
spec/lib/services/profile-api-service-spec.js

Please enter the commit message for your changes. Lines starting

Fixed the logging issue with Arista switches

---

api/rest/templates.js

Signed-off-by: Azzam Tannous <azzam.tannous@emc.com>

Fix return value of the PUT /TEMPLATE api

---

data/templates/startup.ps1

@RackHD/veyron @RackHD/corecommitters

Fix the port in the WinpE microkernel

---

lib/graphs/dell-wsman-get-bios-graph.js

**Background**
As a developer of RACADM replacement work squad, based on the preceding investigation work ( RAC-6170 DONE ), I could start to port RACADM based Get/Set BIOS configuration implementation with WSMAN API.
**Details**
TODO
(1) Based on the gap analysis spreadsheet created from RAC-6170 DONE
(2) Finish the feature code to replace RACADM code with WSMAN API
(3) Finish unit test code
(4) Pass code review and get code merged
**Reviewers**
@anhou @nortonluo @lanchongyizu

[RAC-6209] RACADM based Get BIOS Config implementation with WSMAN API

---

api/swagger.json
test/test_api_templates.py

In the stand alone WFE, we are not loading the views. I removed them from the Swagger yaml file to fix the issue

remove the views from on-taskgraph

---

.gitignore
api/swagger.json
test/test_api_notification.py
test/test_api_workflows.py

Signed-off-by: Anitha Srinivasan <anitha.srinivasan@dell.com>

Added functional test for /notifications &  /workflows

---

test/test_api_tasks.py

Signed-off-by: Azzam Tannous <azzam.tannous@dell.com>

Added test for /Tasks

---

api/swagger.json
test/test_api_profiles.py

Signed-off-by: Azzam Tannous <azzam.tannous@dell.com>

/Profiles test

---

lib/graphs/discovery-sku-orig-graph.js

- This option can be configured in the rackhd config.json file
- to use it, user can set property "discoveryGraph": "Graph.SKU.Orig.Discovery"

Create a Discovery sku graph that use old mikrokernel

---

lib/graphs/get-switch-config-graph.js
lib/graphs/get-switch-version-graph.js
lib/graphs/update-switch-firmware-graph.js

get-switch-config-graph.js
get-switch-version-graph.js
update-switch-firmware-graph.js

Update graph to use task

---

lib/graphs/dell-wsman-delete-volume-graph.js

**Background**
Replace RACADM based RAID operation feature implementation with WSMAN API. This pr is used for deleting volume operation. Here, a new graph is added. Details in https://rackhd.atlassian.net/browse/RAC-6214
depends on: https://github.com/RackHD/on-tasks/pull/558
**Reviewers**
@nortonluo @lanchongyizu @AlaricChan

RAC-6214 : add dell wsman delete volume

---

lib/graphs/dell-wsman-reset-components-graph.js
spec/lib/graphs/dell-wsman-configure-bios-graph-spec.js
spec/lib/graphs/dell-wsman-get-bios-graph-spec.js
spec/lib/graphs/dell-wsman-get-inventory-graph-spec.js
spec/lib/graphs/dell-wsman-reset-components-graph-spec.js

**Background**
Based on the previous investigation result, develop to port Graph.Dell.Racadm.ResetComponents and /Systems/{identifier}/Bios.ResetBios to use WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6481
**Done**
add dell-wsman-reset-components-graph
@RackHD/corecommitters @nortonluo

add dell-wsman-reset-components-graph

---

lib/graphs/dell-wsman-add-volume-graph.js

**Background**
Based on the preceding investigation work (RAC-6212), add volume feature will be implemented with wsman API. One graph will be created which constains four tasks. The first task is used to get xml file for adding volume. The second task is used to update the xml file. The third task is used to add volume. The last task is used to update mongodb.
**Reviewers**
@anhou @nortonluo @lanchongyizu @AlaricChan

RAC-6491 : dell wsman add volume feature implementation with WSMAN API

---

lib/graphs/dell-wsman-configure-idrac-graph.js
spec/lib/graphs/dell-wsman-configure-idrac-graph-spec.js

**Background**
Based on the previous investigation result, develop to port Graph.Dell.Configure.Idrac to use WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6479
**Done**
add dell-wsman-configure-idrac-graph
**Reviewers**
@RackHD/corecommitters @nortonluo @AlaricChan @yaolingling

add dell-wsman-configure-idrac-graph

---

lib/graphs/dell-wsman-simple-update-firmware-graph.js

**Background**
Our target is to replace all the RACADM dependencies with WSMAN in RackHD features. This task aims to replace RACADM with WSMAN graph to update single firmware.
**Details**
Add WSMAN graph to archive single firmware update.
It depends on:RackHD/on-tasks#561
**Reviewer**
@lanchongyizu @yaolingling @nortonluo @leoyjchang

[RAC-6366] Add single firmware update graph using wsman

---

package.json

depends on: https://github.com/rackhd/on-http
@keedya @dalebremner

lock grpc version to ~1.7.0

---

lib/graphs/dell-wsman-configure-redfish-alert-graph.js
spec/lib/graphs/dell-wsman-configure-redfish-alert-graph-spec.js

**Background**
Based on the previous investigation result, develop to port Graph.Dell.Configure.Redfish.Alerting to use WSMAN API.
https://rackhd.atlassian.net/browse/RAC-6478
**DONE**
1. add Graph.Dell.Wsman.Configure.Redfish.Alert and unit test
@RackHD/corecommitters @nortonluo @yaolingling @AlaricChan

Port Graph.Dell.Configure.Redfish.Alerting to use WSMAN API

---

data/templates/install-ubuntu/ubuntu-netplan-interfaces

Signed-off-by: mbeierl <mark.beierl@dell.com>

Fixing comment syntax

---

spec/lib/graphs/dell-wsman-config-services-graph-spec.js

**background**
Add unit tests for WSMAN related jobs and graphs.
https://rackhd.atlassian.net/browse/RAC-6550
**Details**
Add unit tests for WSMAN config service graph.
**Reviewer**
@yaolingling @nortonluo @lanchongyizu

[RAC-6550] Add unit tests for WSMAN config service graph

---

data/templates/install-ubuntu/ubuntu.rackhdcallback

The update-rc.d script expects only 3 #s in the START and END
sections or it will ignore the script.
Signed-off-by: mbeierl <mark.beierl@dell.com>

Fixing number of #s

---

data/templates/centos-ks

- Added support for installing additional packages / group packages
- Cleanup of non-installation so that they can be used as storage disks for HCI use cases

Included support for RHEL 7.2

---

data/templates/unattend_server2012.xml

Signed-off-by: Geoff Reid <Geoff.Reid@dell.com>
depends on: https://github.com/RackHD/on-http/pull/828

fix windows install ipv6 netmask parsing

---

lib/graphs/dell-wsman-add-hotspare-graph.js
spec/lib/graphs/dell-wsman-add-hotspare-graph-spec.js

**Background**
This story is to implement adding hot spare via WSMAN, replace the RACADM dependencies in Redfish API with WSMAN implementation.
**Details**
1. create new graph
2. add UT
**Dependency**
depends on: https://github.com/RackHD/on-tasks/pull/576
**Reviewer**
@yaolingling @pengz1 @nortonluo

[RAC-6492] Create graph to add hotspare via WSMAN

---

data/templates/megaraid-config.sh

Graph.Bootstrap.Megaraid.Configure failed to create VD on Dell Servers with perccli64 when the drives are online.
https://rackhd.atlassian.net/browse/RAC-6583
The root cause is that we use storcli64 to find the ID of the virtual disk when the drives are online.
The solution is to replace `storcli64 /c0` with `$path /c$controller`.
@RackHD/corecommitters @pengz1

fix bug in megaraid-config.sh

---

lib/graphs/dell-wsman-discovery-graph.js
spec/lib/graphs/dell-wsman-discovery-graph-spec.js

**Background**
Add unit tests for WSMAN feature related graphs, tasks and jobs.
**Details**
Add unit test for wsman discovery graph.
**Reviewer**
@pengz1 @yaolingling @nortonluo @lanchongyizu

[RAC-6551] Create unit tests for wsman discovery graph

---

lib/graphs/bootstrap-rancher-graph.js
spec/lib/graphs/bootstrap-rancher-graph-spec.js

**Background**
We need Graph.BootstrapRancher for debugging. Please refer to https://rackhd.readthedocs.io/en/latest/rackhd/microkernel.html#how-to-login-microkernel
**Done**
Add Graph.BootstrapRancher
@RackHD/corecommitters @pengz1 @nortonluo

add Graph.BootstrapRancher

---

data/templates/cloud-config.yaml

**Background**
User can't ssh into RancherOS.
**Done**
Fix the issue that user can't ssh into RancherOS
@RackHD/corecommitters @keedya @pengz1 @nortonluo

Fix the issue that user can't ssh into RancherOS

---

data/profiles/rancherOS.ipxe

Enable netconsole as @keedya proposed in slack.
@RackHD/corecommitters @keedya @pengz1 @nortonluo

enable netconsole

---

lib/graphs/dell-racadm-reset-components-graph.js

add schema for Graph.Dell.Racadm.ResetComponents otherwise the defaults options won't work.
https://rackhd.atlassian.net/browse/RAC-6514
@RackHD/corecommitters @iceiilin @nortonluo

add schema for Graph.Dell.Racadm.ResetComponents

---

data/templates/winpe-kickstart.ps1

OS installation job uses powershell script to prepare for Windows Server installation. The script doesn't throw an error but notify RackHD by a POST command about its completion, which results in the success of the job while it actually fails.
This PR modify the script to catch failures and post notifications with this error message to RackHD.
PR https://github.com/RackHD/on-tasks/pull/592 added error handling in OS installation job.

[RAC-6712] Add error handling for winpe kickstart file

---

data/templates/dell-switch-nos-install.sh
lib/graphs/dell-switch-nos-install-graph.js

@markbeierl @dalebremner @geoff-reid

Enable Nos installation on the Dell switch s6000

---

data/templates/centos-ks
data/templates/esx-ks
data/templates/install-debian/debian-interfaces
data/templates/install-debian/debian-preseed
data/templates/install-photon/post-install-photon.sh
data/templates/pxe-cloud-config.yml
data/templates/suse-autoinst.xml
data/templates/unattend_server2012.xml

Fixed ipv6 configuration in ESXi, Windows, Debian, Centos, Suse, and Photon.
TODO: Teeeeeeeeeeeeeeeeeeeeeeeeest...........
Verified:
- ESXi
- Centos
- Ubuntu
Paired with @PengTian0 
@lanchongyizu @iceiilin @pengz1 @PengTian0

[RAC-6563] fix esx-ks ipv6 format
